/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.Heroe;
import modelo.Malvado;

/**
 *
 * @author Lau
 */
public class Pantalla_prueba extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla_prueba
     */
    public Pantalla_prueba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        miPanel = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        batalla_bt = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Batalla SuperX");

        miPanel.setBackground(new java.awt.Color(248, 132, 41));

        titulo.setBackground(new java.awt.Color(255, 128, 0));
        titulo.setFont(new java.awt.Font("LM Sans Quot 8", 1, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(180, 22, 22));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("LA GRAN PELEA");

        batalla_bt.setBackground(java.awt.Color.red);
        batalla_bt.setFont(new java.awt.Font("AnjaliOldLipi", 1, 24)); // NOI18N
        batalla_bt.setForeground(new java.awt.Color(1, 1, 1));
        batalla_bt.setText("INICIAR BATALLA");
        batalla_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalla_btActionPerformed(evt);
            }
        });

        jTextArea1.setBackground(new java.awt.Color(237, 200, 90));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Manjari Bold", 0, 24)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout miPanelLayout = new javax.swing.GroupLayout(miPanel);
        miPanel.setLayout(miPanelLayout);
        miPanelLayout.setHorizontalGroup(
            miPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(miPanelLayout.createSequentialGroup()
                .addGroup(miPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(miPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(batalla_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(miPanelLayout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        miPanelLayout.setVerticalGroup(
            miPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(miPanelLayout.createSequentialGroup()
                .addGroup(miPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(miPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(miPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(batalla_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(miPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(miPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void batalla_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalla_btActionPerformed
        // TODO add your handling code here:
        Malvado evil = new Malvado(8, 100, "Ramon", "Buenos Aires", "tirar Rayos");
        Heroe hero = new Heroe (10, 100, "Lidia", "Buenos Aires", "Controla la mente");
        System.out.println("Malvado " + evil.getNombre() + " VS heroico " + hero.getNombre());
        jTextArea1.append("Malvado " + evil.getNombre() + " VS heroico " + hero.getNombre()+"\n");
       
        
        while (evil.getEnergia() > 0 && hero.getEnergia() > 0){
        
        int poder_malvado;
        int poder_heroe;
        poder_malvado = (int) Math.floor(Math.random() * (4-1+1) + (1));
          switch(poder_malvado){
            case 1 -> {hero.debilitar(evil.Rayo_violeta());
            jTextArea1.append("---El villano ataca con Rayo violeta---\n");}
            case 2 -> {hero.debilitar(evil.Rayo_verde());
            jTextArea1.append("---El villano ataca con Rayo verde---\n");}
            
            case 3 -> {hero.debilitar(evil.Rayo_azul());
            jTextArea1.append("---El villano ataca con Rayo azul---\n");
            }
            case 4 -> {hero.debilitar(evil.Rayo_rojo());
            jTextArea1.append("---El villano ataca con Rayo rojo---\n");
            }
            default -> {hero.debilitar(evil.Rayo_rojo());
            jTextArea1.append("---El villano ataca con Rayo rojo---\n");}
          }
           System.out.println(hero.toString() + System.lineSeparator());
           jTextArea1.append(hero.toString()+"\n");
          //**********************************************************//
          
          poder_heroe = (int) Math.floor(Math.random() * (4-1+1) + (1));
          switch(poder_heroe) {
            case 1 -> {evil.debilitar(hero.Controla_oxipital());
            jTextArea1.append("---El heroe ataca con Control oxipital---\n");}
            case 2 -> {evil.debilitar(hero.Controla_cerebelo());
            jTextArea1.append("---El heroe ataca con Control cerebelo---\n");}
            case 3 -> {evil.debilitar(hero.Controla_lobulo_temporal());
            jTextArea1.append("---El heroe ataca con Control lobulo temporal---\n");}
            case 4 -> {evil.debilitar(hero.Lobulo_frontal());
            jTextArea1.append("---El heroe ataca con Lobulo frontal---\n");}
            default -> {evil.debilitar(hero.Lobulo_frontal());
            jTextArea1.append("---El heroe ataca con Lobulo frontal---\n");}
          }
          System.out.println(evil.toString() + System.lineSeparator());
          jTextArea1.append(evil.toString()+"\n");
          //if(poder_malvado < poder_heroe){
           //   System.out.println("Gana el malo esta pelea" + System.lineSeparator());
         // }
         // if(poder_heroe < poder_malvado){
         //     System.out.println("Gana el bueno esta pelea" + System.lineSeparator());  
         // }
          //if(poder_heroe == poder_malvado){
           //   System.out.println("Ambos sufren el mismo daño en esta pelea" + System.lineSeparator());  
         // }
          //*System.out.println(malvado.toString()); texto_resultado.append(malvado.toString()+"\n");**//
        }
          if(evil.getEnergia()<=0 && hero.getEnergia()<=0){
              System.out.println("al final murieron ambos ");
              jTextArea1.append("al final murieron ambos\n");
          }
          else{
            if(evil.getEnergia()<=0 && hero.getEnergia()>=0){
              System.out.println("murio el malo al final, gana el Heroe");
              jTextArea1.append("murio el malo al final, gana el Heroe\n");
            }
             if(evil.getEnergia()>=0 && hero.getEnergia()<=0){
              System.out.println("murio el heroe al final, gana el villano");
              jTextArea1.append("murio el heroe al final, gana el villano\n");
             }
          }   
    }//GEN-LAST:event_batalla_btActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla_prueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batalla_bt;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel miPanel;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
